version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::084375576167:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-RlWwxJXBTBrT"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::084375576167:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-4VtHqYfN8OvT"
cloudformation_execution_role = "arn:aws:iam::084375576167:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-dytcdS7SExlI"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-10ymo5dt171c"
image_repository = ""
region = "us-east-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::084375576167:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-w8nR1DeUbjM8"
cloudformation_execution_role = "arn:aws:iam::084375576167:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-ScGbcCvJBesd"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-8dleefqnqnh8"
image_repository = ""
region = "us-east-1"
